services:
  dagster:
    build:
      context: .
      dockerfile: docker/dagster.Dockerfile
    ports:
      - 3000:3000
  postgres:
    build: 
      context: .
      dockerfile: docker/PostgreSQL.Dockerfile
    ports:
      - 5432:5432
    volumes:
      - dagster-postgres:/var/lib/postgresql@15/data
volumes:
  dagster-postgres:
    driver: local